### ISSUE TITLE
请问如何测试TimingInterceptor？

### ISSUE THREAD

**Issue by koushui** [yulewei/javaagent-demo#1]
请问如何测试agentmain模式下的TimerAgent，能否私信给个微信请教一下？
我修改了一下TimerAgent，添加了agentmain，结果测试的时候报错：

Exception in thread "Attach Listener" java.lang.NoSuchMethodException: com.demo.TimerAgent.agentmain(java.lang.String, java.lang.instrument.Instrumentation)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:327)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Agent failed to start!
Exception in thread "main" java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@17a7cec2
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:384)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:233)
        at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:208)
        at com.demo.AgentLoader2.main(AgentLoader2.java:30)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.bytebuddy.agent.Attacher.install(Attacher.java:88)
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:379)
        ... 3 more
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        ... 9 more

**Comment by yulewei** [comment]
可以看下这个，agentmain 不支持 interception API
https://github.com/raphw/byte-buddy/issues/110#issuecomment-204619688

**Comment by yulewei** [comment]
示例代码现在添加了 com.demo.TimerAgent#agentmain，使用 bytebuddy 的 Advice 实现。另外完善了 README 文件
